

extends Node



onready var MOTHERSHIP_TILE_DATA = [
	
	# top row
	{
		'fixture_id': 'a',
		'x': 0,
		'y': 0,
		'location_description': 'top_left',
		'tile_code': 15,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': true,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'b',
		'x': 1,
		'y': 0,
		'location_description': null,
		'tile_code': 14,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'c',
		'x': 2,
		'y': 0,
		'location_description': null,
		'tile_code': 14,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'd',
		'x': 3,
		'y': 0,
		'location_description': 'top_right',
		'tile_code': 15,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	
	# middle row
	{
		'fixture_id': 'e',
		'x': 0,
		'y': 1,
		'location_description': null,
		'tile_code': 14,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'f',
		'x': 1,
		'y': 1,
		'location_description': null,
		'tile_code': 18,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': true,
		'health': 50,
	},
	{
		'fixture_id': 'g',
		'x': 2,
		'y': 1,
		'location_description': null,
		'tile_code': 18,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': true,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': true,
		'health': 50,
	},
	{
		'fixture_id': 'h',
		'x': 3,
		'y': 1,
		'location_description': null,
		'tile_code': 14,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	
	# bottom row
	{
		'fixture_id': 'i',
		'x': 0,
		'y': 2,
		'location_description': 'bottom_left',
		'tile_code': 14,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'j',
		'x': 1,
		'y': 2,
		'location_description': null,
		'tile_code': 16,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': true,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'k',
		'x': 2,
		'y': 2,
		'location_description': null,
		'tile_code': 16,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': true,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
	{
		'fixture_id': 'l',
		'x': 3,
		'y': 2,
		'location_description': 'bottom_right',
		'tile_code': 14,
		'mini_tile_code': 6,
		'tile_map_set_cell_flip_x': false,
		'tile_map_set_cell_flip_y': false,
		'tile_map_set_cell_transpose': false,
		'health': 50,
	},
]




